administration/urls.py
from django.urls import path
from . import views

app_name = "administration"

urlpatterns = [
    # Dashboard
    path('', views.dashboardview, name="dashboard"),

    # Digital Wills
    path('digital-wills', views.digitalwillview, name="digitalwill"),

    # Heir Management
    path('digital-wills/heir/update/<str:heir_id>/', views.digitalwillUpdateHeirview, name="digitalwillupdateheir"),
    path('digital-wills/heir/delete/<str:heir_id>/', views.digitalwillDeleteHeirview, name="digitalwilldeleteteheir"),

    # Special Account Management
    path('digital-wills/special_account/update/<str:special_account_id>/', views.digitalwillUpdateSpecialAccountview, name='digitalwillspecialaccount'),
    path('digital-wills/special_account/verify_update/<str:token>/', views.verify_special_account_update, name='verify_special_account_update'),
    path('digital-wills/special_account/delete/<uuid:special_account_id>/', views.request_delete_special_account, name='deletespecialaccount'),
    path('digital-wills/special_account/delete/confirm/<uuid:token>/', views.confirm_delete_special_account, name='confirm_delete_special_account'),

    # Asset Management
    path('digital-wills/asset/update/<str:asset_id>/', views.digitalwillUpdateAssetview, name="digitalwillupdateasset"),
    path('digital-wills/asset/delete/<str:asset_id>/', views.digitalwillDeleteAssetview, name="digitalwilldeleteteasset"),

    # Email Verification
    path('verify-heir/<str:token>/', views.verify_heir_view, name="verify_heir"),
    path('verify-asset/<str:token>/', views.verify_asset_view, name="verify_asset"),
    path('resend-asset-verification/', views.resend_asset_verification_email, name="resend_asset_verification"),
    path('verify-special-account/<str:token>/', views.verify_special_account, name="verify_special_account"),
    path('resend-special-account-verification/', views.resend_special_account_verification, name="resend_special_account_verification"),
    path('verify-confidential-info/<str:token>/', views.verify_confidential_info, name="verify_confidential_info"),
    path('resend-confidential-info-verification/', views.resend_confidential_info_verification, name="resend_confidential_info_verification"),
    path('verify-executor/<str:token>/', views.verify_executor, name="verify_executor"),
    path('verify-instruction/<str:token>/', views.verify_instruction, name="verify_instruction"),
    path('verify-audio/<str:token>/', views.verify_audio, name="verify_audio"),
    path('verify-asset-update/<str:token>/', views.verify_asset_update, name="verify_asset_update"),
    path('verify-asset-delete/<str:token>/', views.verify_asset_delete, name="verify_asset_delete"),

    # Confidential Info Management
    path('confidential-info/update/<uuid:id>/', views.update_confidential_info, name='update_confidential_info'),
    path('confirm-update/<uidb64>/<token>/', views.confirm_update_confidential_info, name='confirm_update_confidential_info'),
    path('confidential-info/delete/request/<uuid:id>/', views.request_delete_confidential_info, name='request_delete_confidential_info'),
    path('confidential-info/delete/confirm/<uidb64>/<token>/', views.confirm_delete_confidential_info, name='confirm_delete_confidential_info'),

    # Executor Management
    path('executor/update/request/<uuid:id>/', views.request_update_executor, name='request_update_executor'),
    path('executor/update/confirm/<uidb64>/<token>/', views.confirm_update_executor, name='confirm_update_executor'),
    path('executor/delete/request/<uuid:id>/', views.request_delete_executor, name='request_delete_executor'),
    path('executor/delete/confirm/<uidb64>/<token>/', views.confirm_delete_executor, name='confirm_delete_executor'),

    # Post-Death Instructions
    path('post-death/update/request/<uuid:id>/', views.request_update_post_death, name='request_update_post_death'),
    path('post-death/update/confirm/<uidb64>/<token>/', views.confirm_update_post_death, name='confirm_update_post_death'),
    path('post-death/delete/request/<uuid:id>/', views.request_delete_post_death_instruction, name='request_delete_post_death_instruction'),
    path('post-death/delete/confirm/<uidb64>/<token>/', views.confirm_delete_post_death_instruction, name='confirm_delete_post_death_instruction'),

    # Audio Instructions
    path('audio/update/request/<uuid:id>/', views.request_update_audio_instruction, name='request_update_audio_instruction'),
    path('audio/update/confirm/<uidb64>/<token>/', views.confirm_update_audio_instruction, name='confirm_update_audio_instruction'),
    path('audio/delete/request/<uuid:id>/', views.request_delete_audio_instruction, name='request_delete_audio_instruction'),
    path('audio/delete/confirm/<uidb64>/<token>/', views.confirm_delete_audio_instruction, name='confirm_delete_audio_instruction'),

    path('beneficiary/', views.beneficiaryview, name="beneficiary"),
]

authentication/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetView

app_name = "authentication"

urlpatterns = [
    path('', views.loginview, name="auth"),
    path('registration/', views.registerview, name="registration"),
    path("authenticationverify-email/<uidb64>/<token>/", views.verify_email_view, name="verify_email"),
    path('logout/', views.logoutview, name="logout"),
    path('user/personal-info/',views.personalinformationview, name="personalinformation"),
    path("verify-email/<token>/", views.verify_email, name="verify_email"),

    path("account-settings/", views.accountsettingview, name="accountsetting"),
    path("account-settings/delete/user/<str:user_id>/", views.deleteuseraccountview, name="deleteuseraccount"),
    path("account-settings/update/<str:user_id>/", views.updateuseraccountview, name="updateuseraccount"),

    # Password reset
    # Use the custom PasswordResetView here
    path('password_reset/', 
         views.CustomPasswordResetView.as_view(), 
         name='password_reset'),
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), 
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), 
         name='password_reset_confirm'),
    path('reset/done/', 
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
         name='password_reset_complete'),
]

password_urlpatterns = [
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += password_urlpatterns

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("digitalwillclient.urls", namespace="digitalwillclient")),
    path('authentication', include("authentication.urls", namespace="authentication")),
    path('administration/', include("administration.urls", namespace="administration"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digital Will - {% block title %}{% endblock %}</title>
    
    <!-- Bootstrap 5.2.3 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>

    {% block content %}{% endblock %}

<!-- Bootstrap JS Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
{% if messages %}
  {% for message in messages %}
    <script>
      Swal.fire({
        toast: true,
        position: 'top-end',
        icon: '{% if "success" in message.tags %}success{% elif "error" in message.tags %}error{% elif "warning" in message.tags %}warning{% else %}info{% endif %}',
        title: '{{ message|escapejs }}',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
        didOpen: (toast) => {
          toast.addEventListener('mouseenter', Swal.stopTimer)
          toast.addEventListener('mouseleave', Swal.resumeTimer)
        }
      });
    </script>
  {% endfor %}
{% endif %}
</body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}{% endblock %} - Digital Willing</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <!-- Select2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <!-- jQuery (required for Select2) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Select2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>
<body>

    <!-- Sidebar -->
    <div id="sidebar" class="sidebar">
        <a href="{% url 'administration:dashboard' %}"><i class="bi bi-speedometer2 me-2"></i> Dashboard</a>
        <a href="{% url 'authentication:personalinformation' %}"><i class="bi bi-person-circle"></i> Personal Information</a>
        <a href="{% url 'administration:digitalwill' %}"><i class="bi bi-file-earmark-text me-2"></i> Digital Wills</a>
        <a href="{% url 'administration:beneficiary' %}"><i class="bi bi-people-fill me-2"></i> Beneficiaries</a>
        {% if request.user.user_userprofile.roles == 'Admin' %}
        <a href="{% url 'authentication:accountsetting' %}"><i class="bi bi-gear-fill me-2"></i> Account Settings</a>
        {% endif %}
        <a href="" data-bs-toggle="modal" data-bs-target="#logoutModel"><i class="bi bi-box-arrow-right me-2"></i> Logout</a>
    </div>

    <!-- Topbar -->
    <div class="topbar">
        <button class="toggle-btn" onclick="toggleSidebar()">☰</button>
        <div class="d-flex justify-content-center align-items-center gap-2">
            <div>
                <a href="{% url 'administration:dashboard' %}" class="text-white text-decoration-none">Digital Wills </a>
            </div>
            <div>
                <i class="bi bi-person-circle"></i>
                <span>{{request.user}}</span>
            </div>
        </div>
    </div>

    <!-- Main Content -->
    <div id="main" class="main-content">
        {% block content %}{% endblock %}
        <div class="footer-content text-center">
            <p style="color: var(--main-orange);">&copy; copyright seduta will - {% block footer %}{% endblock %} all right reserved.</p>
        </div>
    </div>

    <div class="modal fade" id="logoutModel" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="logoutModel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="logoutModelLabel">Logout Confirmation</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="profile_update_form">
                        <form action="{% url 'authentication:logout' %}" method="POST">
                            {% csrf_token %}
                            <p>Are you sure you want to logout ?</p>
                            <div class="form-group d-flex justify-content-end gap-2">
                            <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" name="logout_user_btn" class="btn btn-sm btn-danger">Logout</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.colVis.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2({
            placeholder: "Select an option",
            allowClear: true
            });
        });
    </script>

    <script>
        function toggleSidebar() {
            const sidebar = document.getElementById('sidebar');
            const main = document.getElementById('main');
            sidebar.classList.toggle('collapsed');
            main.classList.toggle('full');
        }
    </script>
    {% if messages %}
    {% for message in messages %}
        <script>
        Swal.fire({
            toast: true,
            position: 'top-end',
            icon: '{% if "success" in message.tags %}success{% elif "error" in message.tags %}error{% elif "warning" in message.tags %}warning{% else %}info{% endif %}',
            title: '{{ message|escapejs }}',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
            toast.addEventListener('mouseenter', Swal.stopTimer)
            toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        });
        </script>
    {% endfor %}
    {% endif %}

    <script>
        $(document).ready(function () {
        // Reusable function to return export config with custom title and filename
        function getTableOptions(tableTitle) {
            const filenameSafe = tableTitle.replace(/\s+/g, '_'); // replace spaces with underscores

            return {
            dom: 'Blfrtip',
            buttons: [
                {
                extend: 'copy',
                title: tableTitle,
                filename: filenameSafe,
                exportOptions: {
                    columns: ':not(:last-child)'
                }
                },
                {
                extend: 'csv',
                title: tableTitle,
                filename: filenameSafe,
                exportOptions: {
                    columns: ':not(:last-child)'
                }
                },
                {
                extend: 'excel',
                title: tableTitle,
                filename: filenameSafe,
                exportOptions: {
                    columns: ':not(:last-child)'
                }
                },
                {
                extend: 'pdf',
                title: tableTitle,
                filename: filenameSafe,
                exportOptions: {
                    columns: ':not(:last-child)'
                }
                },
                {
                extend: 'print',
                title: tableTitle,
                exportOptions: {
                    columns: ':not(:last-child)'
                }
                },
                'colvis'
            ]
            };
        }
        
        // Apply settings to each table with its respective name
        $('#heirtable').DataTable(getTableOptions('Heirs'));
        $('#assetTable').DataTable(getTableOptions('Assets'));
        $('#specialAccountTable').DataTable(getTableOptions('Special Account'));
        $('#confidentialInfoTable').DataTable(getTableOptions('Confidential Info'));
        $('#executorTable').DataTable(getTableOptions('Executors'));
        $('#postDeathInstructionTable').DataTable(getTableOptions('Post Death Instructions'));
        $('#audioInstructionTable').DataTable(getTableOptions('Audio Instructions'));
        $('#useraccount').DataTable(getTableOptions('User Accounts'));
        });

    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
</body>
</html>